### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by MagboneD** [Algorithman/SoundCenSe#15]
I'm getting this error. I have all prerequisites installed, so I'm not sure what is happening here: 
2017-06-28 06:28:56.1483|WARN|SoundCenSeGTK.MainClass|Checking dll in registry
2017-06-28 06:28:56.4915|FATAL|SoundCenSeGTK.MainClass|Uncaught Exception: 
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Gdk.PixbufLoader..ctor()
   at Gdk.PixbufLoader..ctor(Assembly assembly, String resource)
   at Gdk.Pixbuf..ctor(Assembly assembly, String resource)
   at Gdk.Pixbuf.LoadFromResource(String resource)
   at SoundCenSeGTK.MainWindow.Build()
   at SoundCenSeGTK.MainWindow..ctor()
   at SoundCenSeGTK.MainClass.Main(String[] args) System.MissingMethodException

**Comment by Algorithman** [comment]
Odd, never had something like this. And i wonder what !!0[] could be.
According to https://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty-asapp-bundleconfig-registerbundl its about a not installed .net dependency. Could you check if you have .net4 installed (or otherwise change the project to 4.5, recompile and try again). Newer linux may not deliver 4.0 anymore it seems. (at least on my debian stretch the 4.0 folder in /usr/lib/mono/ is empty)

**Comment by Algorithman** [comment]
Ok, found more info on VisualStudio support site:

**Von Microsoft am22.09.2015 um 21:35 bereitgestellt
Hi

Most likely what is happening is that:
- The code is compiling against .NET 4.6, where the reference assemblies include Array.Empty<T>().
- The Roslyn compiler sees that Array.Empty<T> is available and so uses it when generating the empty array needed for the params.
- The compiled app is trying to run on .NET 4.5 where Array.Empty doesn’t exit.

Alex
.NET Framework**

So, updating to .NET 4.6 could work for you.

**Comment by MagboneD** [comment]
Wow, thanks for running that down! I'll give it a try.

**Comment by Algorithman** [comment]
May i ask for your OS version?

**Comment by MagboneD** [comment]
Win7x64 on HP ElitebookZ. .NET is 4.5.2, so it sounds like that's my problem.

**Comment by Algorithman** [comment]
if it works out, i learned something useful again :)

**Comment by Algorithman** [comment]
Closing this for now, let me know if you still have problems.
